Fixed Carousel on smaller screen
ai-economy-simulator/ecosim-client pull request #21
Opened 2024-01-07 13:36 UTC by Ayusht777

#20 
![Screenshot (293)](https://github.com/ai-economy-simulator/ecosim-client/assets/106388215/d807ef07-90e6-48f5-a918-8b5e565b1136)

2024-01-08 19:47 UTC, fliptrail requested changes

2024-01-08 19:47 UTC, fliptrail commented on src/app/components/carousel.tsx
> -            className={styles.flexcontainer}
Don't remove original flexcontainer class. Instead add another class here.

2024-01-08 19:47 UTC, fliptrail commented on src/app/components/carousel.tsx
> +          <div className={styles.CarouselImgContainer}>
Remove

2024-01-08 19:47 UTC, fliptrail commented on src/app/page.module.css
> +@media (max-width: 390px) {
Use breakpoints in accordance with Fluent 2 guidelines. Ref: https://fluent2.microsoft.design/layout#responsive-design

2024-01-08 19:47 UTC, fliptrail commented
@Ayusht777 I've marked up comments.

2024-01-09 05:59 UTC, Ayusht777 commented
check the code now

2024-01-13 09:15 UTC, fliptrail commented
@Ayusht777 npm build is failing
```

Type error: Spread types may only be created from object types.
--
14:42:27.660 |  
14:42:27.660 | 76 \|           <div
14:42:27.660 | 77 \|             className={{
14:42:27.660 | > 78 \|               ...styles.flexcontainer,
14:42:27.660 | \|               ^
14:42:27.660 | 79 \|               ...styles.CarouselImgContainer,
14:42:27.660 | 80 \|             }}
14:42:27.660 | 81 \|           >
14:42:27.775 | Error: Command "npm run build" exited with 1

```

2024-02-11 12:31 UTC, closed without merging